server:
  port: 8080

com:
  topic:
    simple: my.simple.topic
    student: reg.student.engineering
    group: hostel-group

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ${com.my.group}
      auto-offset-reset: earliest
    template:
      default:
        default-topic: ${com.topic.simple}
      anotherTemplate:
        default-topic: ${com.topic.student}